name: Build REAPER Plugin (Multi-Arch)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - arch: 'x64'
            platform: 'x64'
          - arch: 'Win32'
            platform: 'x86'

    steps:
    - name: Checkout plugin repository
      uses: actions/checkout@v4

    # ❗️ ИЗМЕНЕНИЕ: Клонируем SDK с GitHub вместо скачивания
    - name: Checkout REAPER SDK
      uses: actions/checkout@v4
      with:
        repository: 'justinfrankel/reaper-sdk'
        path: 'reaper-sdk'

    - name: Prepare SDK headers
      run: Move-Item -Path reaper-sdk/sdk/* -DestinationPath sdk/
      shell: pwsh

    - name: Build with CMake (${{ matrix.arch }})
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ github.workspace }}/build'
        cmakeAppendedArgs: '-A ${{ matrix.arch }}'

    - name: Upload Windows Artifact (${{ matrix.platform }})
      uses: actions/upload-artifact@v4
      with:
        name: reaper-webview-windows-${{ matrix.platform }}
        path: build/Release/reaper_webview.dll

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout plugin repository
      uses: actions/checkout@v4

    # ❗️ ИЗМЕНЕНИЕ: Клонируем SDK с GitHub вместо скачивания
    - name: Checkout REAPER SDK
      uses: actions/checkout@v4
      with:
        repository: 'justinfrankel/reaper-sdk'
        path: 'reaper-sdk'
    
    - name: Prepare SDK headers
      run: |
        mkdir sdk
        mv reaper-sdk/sdk/* sdk/

    - name: Build with CMake (Universal)
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ github.workspace }}/build'

    - name: Upload macOS Artifact (Universal)
      uses: actions/upload-artifact@v4
      with:
        name: reaper-webview-macos-universal
        path: build/reaper_webview.dylib