name: Build REAPER Plugin (Multi-Arch)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - preset: 'windows-x64'
            platform: 'x64'
          - preset: 'windows-x86'
            platform: 'x86'

    steps:
    - name: Checkout plugin repository
      uses: actions/checkout@v4

    - name: Checkout REAPER SDK
      uses: actions/checkout@v4
      with:
        repository: 'justinfrankel/reaper-sdk'
        path: 'reaper-sdk'

    # ❗️ ВАШЕ ПРЕДЛОЖЕНИЕ: Клонируем WDL как отдельную зависимость
    - name: Checkout WDL library
      uses: actions/checkout@v4
      with:
        repository: 'justinfrankel/WDL'
        path: 'WDL'

    - name: Build with CMake via Preset
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{ matrix.preset }}'
        buildPreset: '${{ matrix.preset }}'

    - name: Upload Windows Artifact (${{ matrix.platform }})
      uses: actions/upload-artifact@v4
      with:
        name: reaper-webview-windows-${{ matrix.platform }}
        path: build/Release/reaper_webview.dll

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout plugin repository
      uses: actions/checkout@v4

    - name: Checkout REAPER SDK
      uses: actions/checkout@v4
      with:
        repository: 'justinfrankel/reaper-sdk'
        path: 'reaper-sdk'

    # ❗️ ВАШЕ ПРЕДЛОЖЕНИЕ: Клонируем WDL как отдельную зависимость
    - name: Checkout WDL library
      uses: actions/checkout@v4
      with:
        repository: 'justinfrankel/WDL'
        path: 'WDL'

    - name: Build with CMake via Preset (Universal)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'macos-universal'
        buildPreset: 'macos-universal'

    - name: Upload macOS Artifact (Universal)
      uses: actions/upload-artifact@v4
      with:
        name: reaper-webview-macos-universal
        path: build/reaper_webview.dylib