name: Build REAPER Plugin (Multi-Arch)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            preset: 'windows-x64'
            platform: 'x64'
            artifact_name: 'reaper_webview.dll'
            artifact_path: 'build/Release/reaper_webview.dll'
          - os: windows-latest
            preset: 'windows-x86'
            platform: 'x86'
            artifact_name: 'reaper_webview.dll'
            artifact_path: 'build/Release/reaper_webview.dll'
          - os: macos-latest
            preset: 'macos-universal'
            platform: 'universal'
            artifact_name: 'reaper_webview.dylib'
            artifact_path: 'build/reaper_webview.dylib'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout plugin repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare dependencies
      run: |
        # Создаем ожидаемую структуру папок
        mkdir -p dependencies/sdk
        ln -sf ../reaper-sdk dependencies/sdk/sdk
        ln -sf ../WDL dependencies/sdk/WDL
        
        # Создаем симлинки для ожидаемой структуры reaper-sdk
        cd dependencies/reaper-sdk
        ln -sf ../../WDL WDL
        cd ../..

    - name: Verify directory structure
      run: |
        ls -la dependencies/
        ls -la dependencies/sdk/
        find dependencies -name "reaper_plugin_functions.h" -o -name "swell.h"
        ls -la dependencies/reaper-sdk/  # Проверяем симлинк в reaper-sdk

    - name: Build with CMake via Preset
      uses: lukka/run-cmake@v10
      with:
        configurePreset: '${{ matrix.preset }}'
        buildPreset: '${{ matrix.preset }}'

    - name: Upload Artifact (${{ matrix.platform }})
      uses: actions/upload-artifact@v4
      with:
        name: reaper-webview-${{ matrix.os }}-${{ matrix.platform }}
        path: ${{ matrix.artifact_path }}